### ISSUE TITLE
Meet an error in init_weights()

### ISSUE THREAD

**Issue by shiningliang** [wang-h/bert-relation-classification#1]
Hello! Thank you for your implementation. I have an error when I ran the code.

python = 3.7
pytorch = 1.2.0
pytorch-transformers = 1.2.0

Traceback (most recent call last):
  File "/home/lab/code/bert-relation-classification/bert.py", line 359, in main
    model = BertForSequenceClassification.from_pretrained(model_dir, config=bertconfig)
  File "/home/lab/anaconda3/lib/python3.7/site-packages/transformers/modeling_utils.py", line 342, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/home/lab/code/bert-relation-classification/model.py", line 66, in __init__
    self.apply(self.init_weights)
  File "/home/lab/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 293, in apply
    module.apply(fn)
  File "/home/lab/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 293, in apply
    module.apply(fn)
  File "/home/lab/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 293, in apply
    module.apply(fn)
  File "/home/lab/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 294, in apply
    fn(self)
TypeError: init_weights() takes 1 positional argument but 2 were given

**Comment by wang-h** [comment]
try pytorch-transformers = 1.1.0

**Comment by shiningliang** [comment]
It works now. Thank you very much.
